# Generated by Django 3.2.7 on 2021-10-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211003_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bids',
            field=models.ManyToManyField(blank=True, null=True, related_name='bids_for_product', to='auctions.Bid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_bid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_bid_for_product', to='auctions.bid'),
        ),
    ]
