# Generated by Django 3.2.7 on 2021-10-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211003_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.ManyToManyField(blank=True, to='auctions.Comment'),
        ),
    ]
