# Generated by Django 3.2.7 on 2021-10-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_product_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_bid_for_product', to='auctions.bid'),
        ),
    ]
